name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "# This workflow will install Python dependencies, run tests and lint with a variety of Python versions"
      - run: echo "The job was automatically triggered by a a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and repository is ${{ github.repository }}"
      - name: Check out the repository code 
        uses: actions/checkout@v3
      - name: List files in the repository
        run: | 
             ls -ltr ${{ github.workspace }}
      - name: check out again
        run: | 
             mkdir test ; ls -ltr ${{ github.workspace }}